# Creating normalized and cumilative player statistics
The player statistics in the CMU data are recorded for the entire season that is the points scored by a player in all the games that they played in that season, we are interested in knowing the statistics per game for a player. If we use the raw data for a season, players which have player more games will have an edge over the players which have played less games. Therefore we normalize these statistics by dividing these attributes by the number of games player each season. Once this is done, for every year we want an average of these statistics including the past years.

In [17]:
import pandas as pd

df = pd.read_csv("player_with_game_id.csv")
gamesDf = pd.read_csv("Kaggle Data/game.csv")

In [18]:
playerRegularSeason = pd.read_csv("Data/player_regular_season.txt")

In [19]:
# Normalize the player stats by dividing stats by games played
playerRegularSeason1 = playerRegularSeason.iloc[:,:7]
playerRegularSeason2 = playerRegularSeason.iloc[:,7:]
playerRegularSeason2Nomarlized = playerRegularSeason2.div(playerRegularSeason1["gp"], axis=0).round(2)
playerRegularSeason2Nomarlized

,minutes,pts,oreb,dreb,reb,asts,stl,blk,turnover,pf,fga,fgm,fta,ftm,tpa,tpm
0,0.00,11.21,0.00,0.00,0.00,0.74,0.00,0.00,0.00,3.43,17.74,4.30,3.79,2.62,0.00,0.0
1,0.00,2.17,0.00,0.00,0.00,0.67,0.00,0.00,0.00,1.53,3.03,0.77,1.17,0.63,0.00,0.0
2,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.25,0.00,0.00,0.00,0.00,0.0
3,0.00,2.38,0.00,0.00,0.00,0.28,0.00,0.00,0.00,1.69,4.53,0.91,1.19,0.55,0.00,0.0
4,0.00,5.09,0.00,0.00,0.00,0.93,0.00,0.00,0.00,2.83,7.55,2.14,1.36,0.81,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19107,8.00,1.74,0.79,0.79,1.58,0.42,0.21,0.32,0.26,1.58,2.16,0.63,0.58,0.47,0.05,0.0
19108,15.82,3.91,1.80,3.09,4.89,0.38,0.18,0.87,0.82,1.73,3.64,1.58,1.31,0.76,0.02,0.0
19109,13.33,3.33,0.67,1.33,2.00,0.00,1.33,0.00,0.67,2.00,4.00,1.67,0.00,0.00,0.00,0.0
19110,9.00,2.33,0.00,0.33,0.33,1.00,1.33,0.00,1.00,0.67,3.67,1.00,0.33,0.33,1.33,0.0
19111,28.59,9.64,2.21,5.45,7.66,1.09,0.72,0.86,1.25,3.14,8.54,4.00,2.48,1.64,0.04,0.0

In [20]:
# Rejoin and form the full table
playerRegularSeasonNormalized = pd.concat([playerRegularSeason1, playerRegularSeason2Nomarlized], axis=1)
playerRegularSeasonNormalized

,ilkid,year,firstname,lastname,team,leag,gp,minutes,pts,oreb,...,stl,blk,turnover,pf,fga,fgm,fta,ftm,tpa,tpm
0,ABRAMJO01,1946,John,Abramovic,PIT,N,47,0.00,11.21,0.00,...,0.00,0.00,0.00,3.43,17.74,4.30,3.79,2.62,0.00,0.0
1,AUBUCCH01,1946,Chet,Aubuchon,DE1,N,30,0.00,2.17,0.00,...,0.00,0.00,0.00,1.53,3.03,0.77,1.17,0.63,0.00,0.0
2,BAKERNO01,1946,Norm,Baker,CH1,N,4,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.25,0.00,0.00,0.00,0.00,0.0
3,BALTIHE01,1946,Herschel,Baltimore,ST1,N,58,0.00,2.38,0.00,...,0.00,0.00,0.00,1.69,4.53,0.91,1.19,0.55,0.00,0.0
4,BARRJO01,1946,John,Barr,ST1,N,58,0.00,5.09,0.00,...,0.00,0.00,0.00,2.83,7.55,2.14,1.36,0.81,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19107,WILLISC01,2004,Scott,Williams,CLE,N,19,8.00,1.74,0.79,...,0.21,0.32,0.26,1.58,2.16,0.63,0.58,0.47,0.05,0.0
19108,WOODSLO01,2004,Loren,Woods,TOR,N,45,15.82,3.91,1.80,...,0.18,0.87,0.82,1.73,3.64,1.58,1.31,0.76,0.02,0.0
19109,WOODSQY01,2004,Qyntel,Woods,MIA,N,3,13.33,3.33,0.67,...,1.33,0.00,0.67,2.00,4.00,1.67,0.00,0.00,0.00,0.0
19110,WRIGHDO01,2004,Dorell,Wright,MIA,N,3,9.00,2.33,0.00,...,1.33,0.00,1.00,0.67,3.67,1.00,0.33,0.33,1.33,0.0
19111,WRIGHLO02,2004,Lorenzen,Wright,MEM,N,80,28.59,9.64,2.21,...,0.72,0.86,1.25,3.14,8.54,4.00,2.48,1.64,0.04,0.0

In [21]:
playerRegularSeasonNormalized.to_csv("player_regular_season_normalized.csv")

In [22]:
playerRegularSeasonNormalized = playerRegularSeasonNormalized[playerRegularSeasonNormalized["year"] >= 1995]
playerRegularSeasonNormalized

,ilkid,year,firstname,lastname,team,leag,gp,minutes,pts,oreb,...,stl,blk,turnover,pf,fga,fgm,fta,ftm,tpa,tpm
13816,ABDULMA01,1995,Mahmo,Abdul-rauf,DEN,N,57,35.60,19.21,0.46,...,1.12,0.05,2.02,2.05,16.75,7.26,2.75,2.56,5.42,2.12
13817,ADAMSMI01,1995,Michael,Adams,CHA,N,21,15.67,5.43,0.24,...,1.00,0.19,1.19,1.19,3.95,1.76,1.67,1.24,1.95,0.67
13818,ADDISRA01,1995,Rafael,Addison,CHA,N,53,9.74,3.23,0.47,...,0.17,0.17,0.51,1.40,3.11,1.45,0.42,0.32,0.17,0.00
13819,ALEXACO01,1995,Cory,Alexander,SAS,N,60,9.33,2.80,0.15,...,0.45,0.03,1.13,1.57,2.58,1.05,0.42,0.27,1.10,0.43
13820,ALLENJE01,1995,Jerome,Allen,MIN,N,41,8.83,2.63,0.12,...,0.51,0.12,0.83,1.02,2.56,0.88,0.88,0.63,0.80,0.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19107,WILLISC01,2004,Scott,Williams,CLE,N,19,8.00,1.74,0.79,...,0.21,0.32,0.26,1.58,2.16,0.63,0.58,0.47,0.05,0.00
19108,WOODSLO01,2004,Loren,Woods,TOR,N,45,15.82,3.91,1.80,...,0.18,0.87,0.82,1.73,3.64,1.58,1.31,0.76,0.02,0.00
19109,WOODSQY01,2004,Qyntel,Woods,MIA,N,3,13.33,3.33,0.67,...,1.33,0.00,0.67,2.00,4.00,1.67,0.00,0.00,0.00,0.00
19110,WRIGHDO01,2004,Dorell,Wright,MIA,N,3,9.00,2.33,0.00,...,1.33,0.00,1.00,0.67,3.67,1.00,0.33,0.33,1.33,0.00
19111,WRIGHLO02,2004,Lorenzen,Wright,MEM,N,80,28.59,9.64,2.21,...,0.72,0.86,1.25,3.14,8.54,4.00,2.48,1.64,0.04,0.00

In [23]:
# I want to calculate a cummalative table where a player stats for 1996 for ex is the stat of 1995
playerRegularSeasonNormalized.sort_values("year", inplace=True)

# Get all columns for cummalative sume
column_names = playerRegularSeasonNormalized.columns.to_list()
relevant_columns = column_names[6:]

# Find cummalative sum for each player for each stat
playerRegularSeasonNormalized['count'] = playerRegularSeasonNormalized.groupby('ilkid').cumcount() + 1
for col in relevant_columns:
    playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
    playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
playerRegularSeasonNormalized

C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized.sort_values("year", inplace=True)
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized['count'] = playerRegularSeasonNormalized.groupby('ilkid').cumcount() + 1
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'{col}_cumsum'] = playerRegularSeasonNormalized.groupby('ilkid')[col].cumsum()
C:\Users\swara\AppData\Local\Temp\ipykernel_14208\3126126749.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  playerRegularSeasonNormalized[f'avg_{col}'] = playerRegularSeasonNormalized[f'{col}_cumsum'] / playerRegularSeasonNormalized['count']

,ilkid,year,firstname,lastname,team,leag,gp,minutes,pts,oreb,...,fgm_cumsum,avg_fgm,fta_cumsum,avg_fta,ftm_cumsum,avg_ftm,tpa_cumsum,avg_tpa,tpm_cumsum,avg_tpm
13816,ABDULMA01,1995,Mahmo,Abdul-rauf,DEN,N,57,35.60,19.21,0.46,...,7.26,7.260000,2.75,2.750000,2.56,2.560000,5.42,5.420000,2.12,2.120000
14188,PIPPESC01,1995,Scottie,Pippen,CHI,N,77,36.69,19.43,1.97,...,7.31,7.310000,4.21,4.210000,2.86,2.860000,5.21,5.210000,1.95,1.950000
14187,PINCKED01,1995,Ed,Pinckney,PHI,N,27,25.15,5.56,2.74,...,2.00,2.000000,2.04,2.040000,1.56,1.560000,0.00,0.000000,0.00,0.000000
14186,PINCKED01,1995,Ed,Pinckney,TOT,N,74,23.11,6.46,2.55,...,4.31,2.155000,4.46,2.230000,3.40,1.700000,0.04,0.020000,0.00,0.000000
14185,PINCKED01,1995,Ed,Pinckney,TOR,N,47,21.94,6.98,2.45,...,6.80,2.266667,7.10,2.366667,5.40,1.800000,0.10,0.033333,0.00,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18723,GILLKE01,2004,Kendall,Gill,MIL,N,14,20.29,6.07,0.79,...,54.79,4.565833,39.30,3.275000,29.84,2.486667,13.92,1.160000,4.18,0.348333
18724,GINOBEM01,2004,Emmanuel,Ginobili,SAS,N,74,29.64,16.03,1.01,...,11.77,3.923333,12.32,4.106667,9.73,3.243333,8.81,2.936667,3.19,1.063333
18725,GIRICGO01,2004,Gordan,Giricek,UTA,N,81,20.49,8.83,0.31,...,30.99,4.427143,16.02,2.288571,13.41,1.915714,17.63,2.518571,6.31,0.901429
18709,FRAHMRI01,2004,Richie,Frahm,POR,N,43,11.60,3.81,0.40,...,2.47,1.235000,1.06,0.530000,0.92,0.460000,3.56,1.780000,1.35,0.675000
19111,WRIGHLO02,2004,Lorenzen,Wright,MEM,N,80,28.59,9.64,2.21,...,34.32,3.813333,22.88,2.542222,15.06,1.673333,0.41,0.045556,0.02,0.002222

In [24]:
playerRegularSeasonNormalized.to_csv("cumilative_player_attributes.csv")