In [36]:
import pandas as pd


pd.set_option('display.max_columns', None)
game = pd.read_csv("Kaggle Data/game.csv")
ts = pd.read_csv("Data/team_season.txt")
pp = pd.read_csv("Data/player_playoffs.txt")
prs = pd.read_csv("Data/player_regular_season.txt")

In [22]:
ts.loc[ts["team"] == "FTW"]

,team,year,leag,o_fgm,o_fga,o_ftm,o_fta,o_oreb,o_dreb,o_reb,o_asts,o_pf,o_stl,o_to,o_blk,o_3pm,o_3pa,o_pts,d_fgm,d_fga,d_ftm,d_fta,d_oreb,d_dreb,d_reb,d_asts,d_pf,d_stl,d_to,d_blk,d_3pm,d_3pa,d_pts,pace,won,lost
22,FTW,1948,N,1536,5370,1385,1979,0,0,0,1082,1722,0,0,0,0,0,4457,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4650,0.0,22,38
36,FTW,1949,N,1878,5901,1634,2331,0,0,0,1364,2065,0,0,0,0,0,5390,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5297,0.0,40,28
50,FTW,1950,N,2002,5927,1718,2387,0,0,3725,1142,1961,0,0,0,0,0,5722,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5848,0.0,32,36
61,FTW,1951,N,1771,5013,1609,2194,0,0,3619,1403,1751,0,0,0,0,0,5151,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5287,0.0,29,37
71,FTW,1952,N,1876,5230,1839,2491,0,0,3548,1438,2119,0,0,0,0,0,5591,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5596,0.0,36,33
81,FTW,1953,N,1952,5187,1689,2315,0,0,3785,1474,1669,0,0,0,0,0,5593,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5479,0.0,40,32
89,FTW,1954,N,2333,5980,1986,2710,0,0,3826,1737,1753,0,0,0,0,0,6652,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6480,0.0,43,29
97,FTW,1955,N,2396,6174,2002,2729,0,0,3974,1752,1789,0,0,0,0,0,6794,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6746,0.0,37,35
105,FTW,1956,N,2532,6612,1874,2510,0,0,4289,1398,1643,0,0,0,0,0,6938,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7106,0.0,34,38

In [39]:
prs.loc[(prs["team"] == "FTW") & (prs["leag"] == "N") & (prs["year"] == 1949)]

,ilkid,year,firstname,lastname,team,leag,gp,minutes,pts,oreb,dreb,reb,asts,stl,blk,turnover,pf,fga,fgm,fta,ftm,tpa,tpm
582,ARMSTPA01,1949,Paul,Armstrong,FTW,N,63,0,458,0,0,0,176,0,0,0.0,217,516,144,241,170,0,0
591,BLACKCH01,1949,Charlie,Black,FTW,N,36,0,382,0,0,0,75,0,0,0.0,140,435,125,209,132,0,0
610,CARPEBO01,1949,Bob,Carpenter,FTW,N,66,0,614,0,0,0,92,0,0,0.0,168,617,212,256,190,0,0
676,HARRIBO01,1949,Bob,Harris,FTW,N,62,0,476,0,0,0,129,0,0,0.0,190,465,168,223,140,0,0
684,HENRYBI01,1949,Bill,Henry,FTW,N,44,0,214,0,0,0,39,0,0,0.0,99,209,65,125,84,0,0
696,JOHNSDA01,1949,David,Johnson,FTW,N,32,0,253,0,0,0,67,0,0,0.0,95,353,110,46,33,0,0
705,KERRIJA01,1949,Jack,Kerris,FTW,N,64,0,457,0,0,0,110,0,0,0.0,162,455,149,248,159,0,0
710,KLIERLE01,1949,Leo,Klier,FTW,N,66,0,455,0,0,0,121,0,0,0.0,177,516,157,190,141,0,0
713,KLUEHDU01,1949,Duane,Klueh,FTW,N,19,0,144,0,0,0,28,0,0,0.0,38,112,49,69,46,0,0
732,MAHNKJO01,1949,John,Mahnken,FTW,N,2,0,7,0,0,0,2,0,0,0.0,8,8,3,3,1,0,0
761,NAGELJE01,1949,Jerry,Nagel,FTW,N,14,0,13,0,0,0,18,0,0,0.0,11,28,6,4,1,0,0
767,NIEMIJO01,1949,John,Niemiera,FTW,N,31,0,174,0,0,0,61,0,0,0.0,42,207,59,73,56,0,0
783,OLDHAJO01,1949,Johnny,Oldham,FTW,N,59,0,357,0,0,0,99,0,0,0.0,192,426,127,145,103,0,0
833,SCHAUFR01,1949,Fred,Schaus,FTW,N,68,0,972,0,0,0,176,0,0,0.0,232,996,351,330,270,0,0
841,SCHULHO01,1949,Howie,Schultz,FTW,N,32,0,271,0,0,0,81,0,0,0.0,119,355,96,122,79,0,0
881,WAGERCL01,1949,Clint,Wager,FTW,N,63,0,143,0,0,0,90,0,0,0.0,175,203,57,47,29,0,0

In [45]:
df1 = game.loc[((game["team_abbreviation_home"] == "FTW") | (game["team_abbreviation_away"] == "FTW")) & (game["game_date"].str.startswith("1949"))]
df1
# len(df1.loc[(game["team_abbreviation_away"] == "FTW") & (game["wl_away"] == "L")].index)
game.loc[(game["team_abbreviation_away"] == "FTW")]

,season_id,team_id_home,team_abbreviation_home,team_name_home,game_id,game_date,matchup_home,wl_home,min,fgm_home,fga_home,fg_pct_home,fg3m_home,fg3a_home,fg3_pct_home,ftm_home,fta_home,ft_pct_home,oreb_home,dreb_home,reb_home,ast_home,stl_home,blk_home,tov_home,pf_home,pts_home,plus_minus_home,video_available_home,team_id_away,team_abbreviation_away,team_name_away,matchup_away,wl_away,fgm_away,fga_away,fg_pct_away,fg3m_away,fg3a_away,fg3_pct_away,ftm_away,fta_away,ft_pct_away,oreb_away,dreb_away,reb_away,ast_away,stl_away,blk_away,tov_away,pf_away,pts_away,plus_minus_away,video_available_away,season_type
575,21948,1610610034,BOM,St. Louis Bombers,24800013,1948-11-06 00:00:00,BOM vs. FTW,W,0,22.0,73.0,0.301,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,65.0,10,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ BOM,L,17.0,92.0,0.185,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,55.0,-10,0,Regular Season
585,21948,1610610032,PRO,Providence Steamrollers,24800022,1948-11-11 00:00:00,PRO vs. FTW,W,0,32.0,NaN,NaN,NaN,NaN,NaN,26.0,39.0,0.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,3,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ PRO,L,34.0,NaN,NaN,NaN,NaN,NaN,19.0,28.0,0.679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.0,-3,0,Regular Season
588,21948,1610612738,BOS,Boston Celtics,24800026,1948-11-12 00:00:00,BOS vs. FTW,W,0,27.0,NaN,NaN,NaN,NaN,NaN,30.0,43.0,0.698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,9,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ BOS,L,29.0,NaN,NaN,NaN,NaN,NaN,17.0,32.0,0.531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.0,-9,0,Regular Season
589,21948,1610610036,WAS,Washington Capitols,24800030,1948-11-13 00:00:00,WAS vs. FTW,W,0,26.0,NaN,NaN,NaN,NaN,NaN,28.0,39.0,0.718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,9,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ WAS,L,23.0,NaN,NaN,NaN,NaN,NaN,25.0,36.0,0.694,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71.0,-9,0,Regular Season
618,21948,1610612744,PHW,Philadelphia Warriors,24800055,1948-11-23 00:00:00,PHW vs. FTW,L,0,31.0,NaN,NaN,NaN,NaN,NaN,18.0,24.0,0.750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,-10,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ PHW,W,35.0,NaN,NaN,NaN,NaN,NaN,20.0,34.0,0.588,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.0,10,0,Regular Season
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3894,21956,1610612744,PHW,Philadelphia Warriors,25600270,1957-03-05 00:00:00,PHW vs. FTW,W,0,48.0,NaN,NaN,NaN,NaN,NaN,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,114.0,34,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ PHW,L,29.0,NaN,NaN,NaN,NaN,NaN,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,80.0,-34,0,Regular Season
3899,21956,1610612744,PHW,Philadelphia Warriors,25600274,1957-03-07 00:00:00,PHW vs. FTW,W,0,41.0,NaN,NaN,NaN,NaN,NaN,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,114.0,14,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ PHW,L,36.0,NaN,NaN,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0,100.0,-14,0,Regular Season
3902,21956,1610612737,STL,St. Louis Hawks,25600279,1957-03-09 00:00:00,STL vs. FTW,W,0,39.0,NaN,NaN,NaN,NaN,NaN,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,97.0,1,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ STL,L,34.0,NaN,NaN,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,96.0,-1,0,Regular Season
3913,21956,1610612737,STL,St. Louis Hawks,25600289,1957-03-14 00:00:00,STL vs. FTW,W,240,44.0,101.0,0.436,NaN,NaN,NaN,27.0,36.0,0.750,NaN,NaN,78.0,NaN,NaN,NaN,NaN,29.0,115.0,12,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ STL,L,34.0,89.0,0.382,NaN,NaN,NaN,35.0,44.0,0.795,NaN,NaN,47.0,NaN,NaN,NaN,NaN,23.0,103.0,-12,0,Regular Season
3916,41956,1610612747,MNL,Minneapolis Lakers,45600211,1957-03-17 00:00:00,MNL vs. FTW,W,0,53.0,NaN,NaN,NaN,NaN,NaN,25.0,34.0,0.735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,131.0,4,0,1610612765,FTW,Ft. Wayne Zollner Pistons,FTW @ MNL,L,50.0,NaN,NaN,NaN,NaN,NaN,27.0,40.0,0.675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,127.0,-4,0,Playoffs

In [46]:
def getTop5Players(players):
    players[['minutes', 'pts','oreb', 'dreb', 'reb', 'asts', 'stl', 'blk', 'turnover', 'pf', 'fga', 'fgm', 'fta', 'ftm', 'tpa', 'tpm']] = players[['minutes', 'pts','oreb', 'dreb', 'reb', 'asts', 'stl', 'blk', 'turnover', 'pf', 'fga', 'fgm', 'fta', 'ftm', 'tpa', 'tpm']].div(players['gp'], axis=0)
    players['score'] = players[['minutes', 'pts','oreb', 'dreb', 'reb', 'asts', 'stl', 'blk', 'turnover', 'pf', 'fga', 'fgm', 'fta', 'ftm', 'tpa', 'tpm']].sum(axis=1)
    return players.nlargest(5, 'score')

In [47]:
playerColumns = ['ilkid', 'gp', 'minutes', 'pts','oreb', 'dreb', 'reb', 'asts', 'stl', 'blk', 'turnover', 'pf', 'fga', 'fgm', 'fta', 'ftm', 'tpa', 'tpm']

columns = ["W_team","L_team"]

for i in range(1,6):
       for col in playerColumns:
              columns.append("W"+str(i)+"_"+col)
for i in range(1,6):
       for col in playerColumns:
              columns.append("L"+str(i)+"_"+col)

team_draft = {}
for index, row in game.iterrows():
       wTeam, lTeam = "team_abbreviation_home", "team_abbreviation_away" if row["wl_home"] == "W" else "team_abbreviation_away", "team_abbreviation_home"
       wPlayers = prs.loc[(prs["team"] == row[wTeam]) & (prs["year"] == row["game_date"][0:4]) & (prs["leag"] == "N")]
       Lplayers = prs.loc[(prs["team"] == row[lTeam]) & (prs["year"] == row["game_date"][0:4]) & (prs["leag"] == "N")]
       wPlayers = getTop5Players(wPlayers)

ValueError: too many values to unpack (expected 2)